### ISSUE TITLE
Add more detailed description about network setup

### ISSUE THREAD

**Issue by BeHom** [hpcng/warewulf-web#2]
In the current documentation only the setup for the boot network is described. Typically, an HPC cluster has more than one network connection. However, the description of the default network does not necessarily show how other networks can be specified using the wwctl command. I would therefore suggest to extend the documentation with some relvant examples. <br>

Setup Infiniband Network:
Prerequisites:
- requires Infiniband driver inside the booted container (not part of the description)

Commands:
- set netmask for ib0 interface 
  *wwctl profile set --netdev ib0 --netmask 255.255.255.0 --netname=ib0* "default"
- set ipaddr and type
  *wwctl node set hpc1 --ipaddr 192.168.1.11 --type=InfiniBand --netname=ib0*
- delete the entries
  *wwctl node set hpc1 --netdel --netname=ib0*
  *wwctl profile set hpc1 --netdel --netname=ib0 "default"*

Important is the parameter --netname which defines the entry in the nodes.conf for the respective network interface. On a running system the netname is typically shown via "*ip link show*".

**Comment by kelbstf** [comment]
Hello BeHorn,


thank you very much for your post!
I am a WW4 newbie, and stumbled upon the same issue.

Dumb question: of course you have that running, otherwise you wouldn't have posted it ;-)
And it probably works the same way for "Ethernet" type of networks, right?

But: can this be considered "officially" supported?

I then would support your proposal to include this in the online doc.
Which by the way i find very good already at this stage. 
It helped me a lot, and i understand that it can't minutely follow the development progress that is made on the code.

**Comment by BeHom** [comment]
Hi kelbstf,
yes works the same on Ethernet type of networks.

Whether this can be considered "officially" supported, I cannot answer.
Who is an official supporter and how is the support defined. 
The wwctl program itself supported this at the time. 

Since the current documentation lags behind the development and commands have changed again in the last releases, such examples can suddenly no longer be valid. 

Nevertheless, from my point of view such examples from real applications make sense and support the implementation of own projects.

**Comment by brianclemens** [comment]
Cleaning up old / inapplicable issues. If this issue is still relevant, please open it in the main warewulf repo (where both code and docs are. This is just the website repo.)
